server:
  port: 18082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
    alibaba:
      seata:
        tx-service-group: tx-gmall-group
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.147.128:3306/guli_sms?characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.147.128
    port: 6379
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/sms/**/*.xml
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.atguigu.gmall.sms.entity
logging:
  level:
    com.atguigu.gmall: debug

