server:
  port: 18085
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.147.128:3306/guli_oms?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 192.168.147.128
    port: 6379
  rabbitmq:
    host: 192.168.147.128
    port: 5672
    virtual-host: /fangbei
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 4
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations:  classpath:mapper/oms/**/*.xml
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.atguigu.gmall.oms.entity
logging:
  level:
    com.atguigu.gmall: debug
